use_frameworks!

target 'SimpleCoreDataCrud_Example' do
  pod 'SimpleCoreDataCrud', :path => '../'

  target 'SimpleCoreDataCrud_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
